version: '3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


volumes:
  postgres_data: