# Generated by Django 3.2.7 on 2021-09-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mark', models.CharField(max_length=50)),
                ('price', models.IntegerField(help_text='Precio del producto')),
                ('stock', models.IntegerField(help_text='Cantidad del producto')),
                ('categories', models.CharField(help_text='Categoria de producto', max_length=50)),
            ],
        ),
    ]
