# Generated by Django 3.2.7 on 2021-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20210911_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'verbose_name': 'Maquina', 'verbose_name_plural': 'Maquinas'},
        ),
        migrations.AddField(
            model_name='machine',
            name='cover_image',
            field=models.ImageField(default=21, upload_to='Portadas/', verbose_name='Imagen de portada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemachine',
            name='image',
            field=models.ImageField(upload_to='machines/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='categories',
            field=models.CharField(help_text='Categoria de producto', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(help_text='Ingrese la descripción completa del producto', max_length=1000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mark',
            field=models.CharField(help_text='Ingrese la marca del producto', max_length=50, verbose_name='Marca del producto'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre completo del producto', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.IntegerField(help_text='Precio del producto', verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='stock',
            field=models.IntegerField(help_text='Cantidad de producto'),
        ),
    ]
