# Generated by Django 3.2.7 on 2021-09-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20210911_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='discount_price',
            field=models.IntegerField(blank=True, help_text='Precio con descuento', null=True, verbose_name='Precio descuento'),
        ),
        migrations.AddField(
            model_name='machine',
            name='discount_rate',
            field=models.IntegerField(blank=True, help_text='Porcentaje del descuento', null=True, verbose_name='Descuento en %'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='categories',
            field=models.CharField(choices=[('RF', 'Refrigeración'), ('GT', 'Gastronomía'), ('PD', 'Panadería'), ('AI', 'Acero Inoxidable'), ('CM', 'Comercio')], help_text='Categoria de producto', max_length=50, verbose_name='Categoria'),
        ),
    ]
