# Generated by Django 3.2.7 on 2021-09-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20210912_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='cover_image',
            field=models.ImageField(help_text='Seleccione una imagen', upload_to='Portadas/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='discount_price',
            field=models.IntegerField(blank=True, help_text='Precio con descuento (No es obligatorio)', null=True, verbose_name='Precio descuento'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='discount_rate',
            field=models.IntegerField(blank=True, help_text='Porcentaje del descuento (No es obligatorio)', null=True, verbose_name='Descuento en %'),
        ),
    ]
