# Generated by Django 3.2.7 on 2022-03-10 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoCamara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Código"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "registroActivo",
                    models.BooleanField(default=True, verbose_name="Registro Activo"),
                ),
                (
                    "registroFechaCreacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Camara",
                "verbose_name_plural": "Tipo de Camara",
                "db_table": "tipoCamara",
            },
        ),
        migrations.CreateModel(
            name="Camara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Código de camara",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre de camara",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Descripción de camara",
                    ),
                ),
                (
                    "peso",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Peso de camara"
                    ),
                ),
                (
                    "voltaje",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Voltaje de camara"
                    ),
                ),
                (
                    "valorUF",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Valor uf de camara"
                    ),
                ),
                (
                    "registroActivo",
                    models.BooleanField(default=True, verbose_name="Registro Activo"),
                ),
                (
                    "registroFechaCreacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppCamara.tipocamara",
                        verbose_name="Tipo de Camara",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camara",
                "verbose_name_plural": "Camara",
                "db_table": "Camara",
            },
        ),
    ]
