# Generated by Django 3.2.7 on 2022-03-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCamara", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camara",
            name="dimension",
            field=models.CharField(
                default=0, max_length=150, verbose_name="Dimensión del camara"
            ),
            preserve_default=False,
        ),
    ]
