# Generated by Django 3.2.7 on 2022-03-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamara', '0002_producto_dimension'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camara',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipocamara',
            table=None,
        ),
    ]
