# Generated by Django 3.2.7 on 2022-03-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamara', '0003_auto_20220311_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocamara',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción'),
        ),
    ]
