# Generated by Django 3.2.7 on 2022-03-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamara', '0004_alter_tipocamara_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='images/default.jpg', upload_to='images/camaras/%Y/%m/', verbose_name='imagen de Camara')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'imagen Camara',
                'verbose_name_plural': 'Imagen Camara',
            },
        ),
        migrations.AlterField(
            model_name='camara',
            name='valorUF',
            field=models.IntegerField(default=None, verbose_name='Valor uf de camara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camara',
            name='imagen',
            field=models.ManyToManyField(blank=True, default=None, to='AppCamara.ImagenCamara', verbose_name='Imagen de Camara'),
        ),
    ]
