# Generated by Django 3.2.7 on 2022-03-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamara', '0005_auto_20220311_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='camara',
            name='voltaje',
        ),
    ]
