# Generated by Django 3.2.7 on 2022-03-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamara', '0006_auto_20220313_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='oferta',
            field=models.BooleanField(default=False, verbose_name='Oferta'),
        ),
    ]
