# Generated by Django 3.2.7 on 2021-09-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdChambers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('RF', 'Refrigeración'), ('CG', 'Congelado')], help_text='Seleccione la categoria de la camara', max_length=20, verbose_name='Categoría')),
                ('dimensions', models.CharField(help_text='Ingrese la longitudes de la camara', max_length=30, verbose_name='Longitudes')),
                ('camera_price', models.IntegerField(help_text='Precio de la camara', verbose_name='Precio de la camara')),
                ('installation_price', models.IntegerField(help_text='Precio de instalación de camara', verbose_name='Precio de instalación')),
                ('description', models.TextField(help_text='Ingrese la descripción de la camara de frío', max_length=1000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Camara de frío',
                'verbose_name_plural': 'Camaras de frío',
                'db_table': 'cold_chamber',
                'ordering': ['id'],
            },
        ),
    ]
