# Generated by Django 3.2.7 on 2021-09-16 02:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chambers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldchambers',
            name='camera_price',
            field=models.IntegerField(help_text='Precio de camara', verbose_name='Precio de camara'),
        ),
        migrations.AlterField(
            model_name='coldchambers',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Ingrese la descripción de la camara de frío', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='coldchambers',
            name='dimensions',
            field=models.CharField(help_text='Ingrese la longitudes de la camara', max_length=30, verbose_name='Dimensiones'),
        ),
    ]
