# Generated by Django 3.2.7 on 2022-03-10 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de Camara',
                'verbose_name_plural': 'Tipo de Camara',
                'db_table': 'tipoCamara',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código de producto')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de producto')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción de producto')),
                ('peso', models.IntegerField(blank=True, null=True, verbose_name='Peso de producto')),
                ('voltaje', models.IntegerField(blank=True, null=True, verbose_name='Voltaje de producto')),
                ('valorUF', models.IntegerField(blank=True, null=True, verbose_name='Valor uf de producto')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('tipo', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProducto.tipoproducto', verbose_name='Tipo de Camara')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'db_table': 'producto',
            },
        ),
    ]
