# Generated by Django 3.2.7 on 2022-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código de producto')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de producto')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción de producto')),
                ('peso', models.IntegerField(blank=True, null=True, verbose_name='Peso de producto')),
                ('voltaje', models.IntegerField(blank=True, null=True, verbose_name='Voltaje de producto')),
                ('valorUF', models.IntegerField(blank=True, null=True, verbose_name='Valor uf de producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen/% Y/% m/% d/', verbose_name='Subir Imagen')),
                ('registroActivo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('registroFechaCreacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'db_table': 'producto',
            },
        ),
    ]
