# Generated by Django 3.2.7 on 2022-03-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProducto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dimension',
            field=models.CharField(default=0, max_length=150, verbose_name='Dimensión del producto'),
            preserve_default=False,
        ),
    ]
